[main]
; Pid文件存储路径
pid_file=/tmp/timer.pid
; 事件通知地址(仅支持http)
notify_url=

[http]
; HTTP 服务监听地址
host = 127.0.0.1
; HTTP 服务监听端口
port = 10010

[log]
; 日志存储目录
dir = /var/log/timer
; 日志等级 0-trace, 1-debug, 2-info, 3-warn, 4-err, 5-critical 6-off
level = 0

[db]
; 数据库文件路径
path = /var/lib/timer/task.db